### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by rberto4** [rberto4/Tesi-FitnessApp-flutter#2]
# UTENTE

### Autenticazione
- [ ] mantenere dati utente anche senza internet in modo da rendere l'app usabile quanto meno per allenarsi e visualizzare i dati 
- [ ] Togliere schermata di Registrazione, in quanto inutile, è il coach a registrare un account. Splash screen/schermata di benvenuto se non si è clienti
### Home utente 
- [ ] Drawer, pulsanti per impostazioni ? 
- [x] Redesign della card allenamento/i del giorno selezionato, mostrare dati tabellari , mostrare orario di allenamento, note e feedback, mostrare storico se allenamento già svolto oppure dati scheda se allenamento è da svolgere. 
- [ ] BottomNavigationBar, trovare un modo per nasconderla quando si scrolla, utile sarebbe lo scroll controll + state managers 
### Tipi esercizi in allenamento 
- [ ] gestire la visualizzazione delle varie tipologie di esercizi (cardio, corpo libero)
- [ ] gestire la visualizzazione dei superset/giant set/drop set
### Timer
- [ ] cambiare scritte quando è attivo
- [ ] Pulsanti per aggiungere o diminuire tempo (?)
- [ ] Sistema per disattivare del tutto il timer
### Scheda
- [ ] Possibilità di aggiungere serie dinamicamente (complicato per gli editext)
### Progressione esercizio
- [ ] #3

# COACH

## Creazione schede 
- [ ] disegnare l'interfaccia grafica per la creazione della scheda di un utente 

### Gestione utenti 
- [ ] mostrare la lista degli utenti seguiti dal coach 
- [ ] per ogni utente mostrare le schede passate 
- [ ] per ogni utente mostrare la scheda attuale con i progressi 

# ESERCIZI 
- [ ] aggiungere le note per ogni singolo esercizio 
## Tipi esercizi 
- [ ] implementare gli esercizi di tipo cardio e corpo libero (lato db) 
- [ ] #4

# NUOVE FEAUTURES + MIGLIORAMENTI 

## User model 
- [ ] Modello di dato utente + extend per Coach e Cliente 
## Chat
- [ ] Implementazione chat testuale
- [ ] capire con chi l'utente può chattare + eventuale "Segreteria"
- [ ] #5
